# Generated by Django 4.2.11 on 2024-04-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_initial'),
        ('user_activities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='item',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.episode', verbose_name='Episode_Comment'),
        ),
        migrations.AddField(
            model_name='follow',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.channel', verbose_name='Channel_Followed'),
        ),
        migrations.AddField(
            model_name='like',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.episode', verbose_name='Episode_liked'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
